apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
      - name: vite-app
        image: CONTAINER_IMAGE
        ports:
        - containerPort: 5173

---

apiVersion: v1
kind: Service
metadata:
  name: vite-app-service
  labels:
    app: vite-app
spec:
  type: NodePort
  selector:
    app: vite-app
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 30001