apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app-deployment
  labels:
    app: vite-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
      - name: vite-app
        image: 125137910162.dkr.ecr.us-east-1.amazonaws.com/vite-app:vite-app-1.0.32
        ports:
        - containerPort: 5173
          name: vite-app
        env:
        - name: VITE_API_URL
          value: http://express-backend-service.default.svc.cluster.local/api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: vite-app-service
  labels:
    app: vite-app
spec:
  type: NodePort
  selector:
    app: vite-app
  ports:
  - port: 5173
    protocol: TCP
    targetPort: 5173
    nodePort: 31444